require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - Rakefile

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/LineLength:
  Max: 120
Style/MixinUsage:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
Style/ClassAndModuleChildren:
  Enabled: false
Style/SignalException:
  Enabled: false
RSpec/NestedGroups:
  Max: 6
RSpec/MultipleExpectations:
  Max: 4
RSpec/SubjectStub:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - test
