version: 2.1

executors:
  default:
    working_directory: ~/ruben
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
      - image: postgres:11.1
        environment:
          POSTGRES_USER: ruben
          POSTGRES_DB: ruben_test
    environment:
        CIRCLE_TEST_REPORTS: test_reports
        MIN_COVERAGE_PERCENTS: 0

caches:
  - &bundle_cache ruben-bundle-v1-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}

commands:
  run_linters:
    steps:
      - run:
          name: Run lintering with lefthook
          command: bundle exec lefthook run pre-commit

  run_specs:
    steps:
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out test_results/rspec/results.xml \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - run:
          name: Stash Coverage Results
          command: |
            mkdir coverage_results
            cp -R coverage/.resultset.json coverage_results/.resultset-${CIRCLE_NODE_INDEX}.json
            ls -lah coverage
            cat coverage/.resultset.json
            cat coverage_results/.resultset-${CIRCLE_NODE_INDEX}.json
  check_coverage:
    steps:
      - attach_workspace:
          at: .
      - run: bundle exec rake simplecov:report_coverage MIN_COVERAGE=$MIN_COVERAGE_PERCENTS

  defaults:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: sudo gem install bundler && bundle install --deployment --jobs 3 --retry 3
      - save_cache:
          key: *bundle_cache
          paths: vendor/bundle
      - run:
          name: Loading schema
          command: RAILS_ENV=test bundle exec rake db:schema:load

jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs
  check_coverage:
    executor: default
    steps:
      - defaults
      - check_coverage

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
      - check_coverage:
          requires:
            - run_specs
