default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= Rails.application.credentials.db[:user] %>
  password: <%= Rails.application.credentials.db[:password] %>

development:
  <<: *default
  database: ruben_development

production:
  <<: *default
  database: ruben

test:
  <<: *default
  database: ruben_test
